### ISSUE TITLE
chore(editorconfig): consider adding it

### ISSUE THREAD

**Issue by jjangga0214** [kookmin-sw/capstone-2020-12#136]
안녕하세요? 

지나가던 인간입니다.

우연인지 필연인지 동영상 및 이미지 화질, fps 향상, Colorization 코드를 찾다가 여기에 당도했네요.

그간의 작업물에 박수를 보냅니다.

다름이 아니라 혹여라도 도움이 되고자 몇가지 이슈를 생성하고자 합니다.

editorconfig는 여러 IDE 가 같은 lint 룰을 따르도록 하는... 어쨌든 좋은 거고 설명은 아래의 링크로 생략하겠습니다. 

권장하고 싶어요! 

https://editorconfig.org

**Comment by Supercraft888** [comment]
Hello!  My name's Alex and I'm a student from Canada.  I'd like to help this project by making a .editorconfig file.  Is this issue still available and something that would be accepted?

**Comment by yun-kwak** [comment]
Hello @Supercraft888!
Yeah, Of course. Please make a PR for that. It would help our project a lot.

@jjangga0214 Thank you for the issues again.

**Comment by Supercraft888** [comment]
Hello!  I made a pull request but when it seemed to have deleted a lot of the other files for some reason, I'll try and solve this as soon as I can.  and make another pull request without the files being deleted

**Comment by Supercraft888** [comment]
I fixed it, the pull request is JUST the editorconfig file now.  So sorry for the previous mistake.
