### ISSUE TITLE
refactor(server): Use temporary table

### ISSUE THREAD

**Issue by gee05053** [kookmin-sw/capstone-2020-12#157]
- 찰나의 상태에 대한 기록 피하자
    - isProcessing -> isProcessed
    - temporary table 생성 후 삭제
    - processing 이전의 애들만 다른 쪽으로 이동

**Comment by yun-kwak** [comment]
[ ] create_media_under_processing_table migration 작성
        * media_under_processing 테이블 생성(
media_under_processing 테이블에 가공중인 미디어의 메타 정보 전체를 저장X mediaId만 저장)
        * media 테이블의 isProcessing 컬럼 삭제
[ ] MediaDB dataSource에 completeProcessing method추가
        * 품질 향상 처리가 완료된 미디어를 media_under_processing에서 지우는 역할을 담당
[ ] MediaDB dataSource의 createMedia 메소드 수정
        * isProcessing column을 작성하는 대신 media_under_processing 테이블에 mediaId 추가
[ ] uploadMedia resolver 수정
        * 품질 향상 처리가 완료되면 isProcessing을 바꾸는 대신 (이제 isProcessing은 없으니) MediaDB dataSource의 completeProcessing method를 호출하도록 수정
