### ISSUE TITLE
UI component들 위치 고정

### ISSUE THREAD

**Issue by gee05053** [kookmin-sw/capstone-2020-12#31]
화면의 크기에 따라 위치가 계속 바뀌는 문제 발생

**Comment by yun-kwak** [comment]
당연히 바뀌어야하는거 아닌가요? 고정을 왜 시키죠?

**Comment by gee05053** [comment]
말이 좀 이상하긴 한데 자신의 위치에서 옮겨가서 다른 컴포넌트들과 겹치는 문제가 발생합니다

**Comment by Lhyejin** [comment]
css 문제네요 아마 프론트 다들 그럴거에요.
