### ISSUE TITLE
Topnavbar 추가 수정

### ISSUE THREAD

**Issue by gee05053** [kookmin-sw/capstone-2020-12#45]
- [x] navbar 테두리
- [x] 로고 바꾸기(한줄로 되어있는걸로)
- [x] navbar 반응형 디자인
- [x] navbar 서치 엔터 눌렀을 때 검색되게
- [x] navbar 아이콘 수정

**Comment by W-C-G** [comment]
스크린페이지에서 로고가 정상적으로 보이기는하는데, 화면을 반으로 줄이면 Memories에서 Memori까지만 나와요.
navbar 반응형 디자인에 이 문제도 포함되어있나요?

**Comment by gee05053** [comment]
> 스크린페이지에서 로고가 정상적으로 보이기는하는데, 화면을 반으로 줄이면 Memories에서 Memori까지만 나와요.
> navbar 반응형 디자인에 이 문제도 포함되어있나요?

네 input을 고정시켜야할거 같아요
