### ISSUE TITLE
media detail로 넘어갈 때 에러 문제

### ISSUE THREAD

**Issue by gee05053** [kookmin-sw/capstone-2020-12#85]
search 진행 → 카드 하나 클릭 → 에러 발생 → 뒤로가기 → 동일 카드 선택 → 정상 작동
특정 카드만 이런문제가 발생하는게 아니라 전체 카드가 이런식으로 동작

Error: "GraphQL error: Undefined binding(s) detected when compiling FIRST. Undefined column(s): [id] query: select "name" from "user" where "id" = ? limit ? GraphQL error: Undefined binding(s) detected when compiling FIRST. Undefined column(s): [id] query: select "profileImgUrl" from "user" where "id" = ? limit ?"

**Comment by gee05053** [comment]
search query
![스크린샷, 2020-05-05 20-51-27](https://user-images.githubusercontent.com/28584221/81063265-7a2a5780-8f12-11ea-95d1-93f6063bf384.png)

media query
![스크린샷, 2020-05-05 20-52-50](https://user-images.githubusercontent.com/28584221/81063273-7c8cb180-8f12-11ea-8931-dbca2427be35.png)

**Comment by yun-kwak** [comment]
해결
